version: '2'
services:
  fluentd:
    build: ./fluentd/
    depends_on:
      - elasticsearch
    expose:
      - 24224
    ports:
      - 24224:24224
    restart: on-failure
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    expose:
      - 9200
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    restart: on-failure
  grafana:
    image: grafana/grafana:4.6.3
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:rw
    restart: on-failure
  grafana-import:
    build: ./grafana/imports/
    depends_on:
      - grafana
  hdfs-krb5:
    image: nlesc/xenon-hdfs-kerberos:latest
    ports:
      - 88:88/tcp
      - 88:88/udp
      - 8020:8020
      - 50010:50010
      - 50470:50470
      - 50475:50475
    restart: on-failure
  postgres-ssl:
    image: nimbustech/postgres-ssl:9.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=postgres
    # volumes:
      # - ./postgres-ssl/data/:/var/lib/postgresql/data
      # - ./postgres-ssl/ssl/:/var/ssl/
    restart: on-failure
